# Install a full build profile with testing & scanning supply chain

profile: build
ceip_policy_disclosed: true

buildservice:
  kp_default_repository: $REGISTRY_SERVER/$REGISTRY_TBS_REPO
  kp_default_repository_secret:
    name: registry-credentials-tbs
    namespace: $INSTALL_NS
  tanzunet_secret:
    name: tanzunet-registry-creds-tbs
    namespace: $INSTALL_NS
  enable_automatic_dependency_updates: false

supply_chain: testing_scanning

ootb_supply_chain_testing_scanning:
  registry:
    server: $REGISTRY_SERVER
    repository: $REGISTRY_TBS_REPO
  gitops:
    ssh_secret: ""

scanning:
  metadataStore:
    url: ""

grype:
  targetImagePullSecret: tanzunet-registry-creds