kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
        endpoint = ["http://local-registry:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."localhost:5001".tls]
        insecure_skip_verify = true
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
   - containerPort: 31090 # expose port 31090 of the node to port 80 on the host for use later by Contour ingress (envoy)
     hostPort: 443
   - containerPort: 31080 # expose port 31080 of the node to port 80 on the host for use later by Contour ingress (envoy)
     hostPort: 80
   - containerPort: 30053 # expose CoreDNS port to port 53 on the host machine
     hostPort: 53
     protocol: udp
   - containerPort: 30053 # expose CoreDNS port to port 53 on the host machine
     hostPort: 53
     protocol: tcp
